# Generated by Django 4.2.3 on 2023-08-01 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ability", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Rarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rarity", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Stats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attack", models.IntegerField()),
                ("defense", models.IntegerField()),
                ("health", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Cookie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "ability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cookie.ability"
                    ),
                ),
                (
                    "rarity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cookie.rarity"
                    ),
                ),
                (
                    "stats",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cookie.stats"
                    ),
                ),
            ],
        ),
    ]
